// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAocLolxTcrvkwTCHN58ze3dL_cp4NDqaw',
    appId: '1:164055371792:web:f06afa0d8528e2b0183a95',
    messagingSenderId: '164055371792',
    projectId: 'fir-fcm-2350d',
    authDomain: 'fir-fcm-2350d.firebaseapp.com',
    storageBucket: 'fir-fcm-2350d.appspot.com',
    measurementId: 'G-HDT7HJT39Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTB1FpiTL3mckEYRmY-jjWVYoyIQ299mk',
    appId: '1:164055371792:android:b79638e4e6a7f4f7183a95',
    messagingSenderId: '164055371792',
    projectId: 'fir-fcm-2350d',
    storageBucket: 'fir-fcm-2350d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFEUbhDadkG84L0WyyOmkgZwjTCNmqoEo',
    appId: '1:164055371792:ios:8ad6a59935984e18183a95',
    messagingSenderId: '164055371792',
    projectId: 'fir-fcm-2350d',
    storageBucket: 'fir-fcm-2350d.appspot.com',
    iosBundleId: 'com.example.fcmFlutter',
  );
}
